stages:
  - build
  - test
  - deploy

build-package:
  stage: build
  image: rust:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y python3-pip python3-venv build-essential patchelf
  script:
    # Build the Rust static library first as it's required by setup.py
    - make rust
    # Install build tools, setuptools_scm, and auditwheel
    - pip install --break-system-packages setuptools wheel auditwheel setuptools-scm
    # Build the wheel
    - python3 setup.py bdist_wheel
    # Repair the wheel to be manylinux compatible
    - auditwheel repair dist/*.whl -w dist/
    # Remove the original non-compliant wheel
    - rm dist/*-linux_x86_64.whl
    # Build the source distribution
    - python3 setup.py sdist
  artifacts:
    paths:
      - dist/


run-tests:
  stage: test
  image: rust:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y python3-pip python3-venv build-essential patchelf
  script:
    - make test

deploy-pypi:
  stage: deploy
  image: python:3.11-slim

  # --- ADD THIS BLOCK ---
  # This forces Twine to use your token instead of looking for OIDC
  variables:
    TWINE_USERNAME: "__token__"
    TWINE_PASSWORD: $TWINE_PASSWORD
  # ----------------------

  script:
    - pip install twine
    # Upload to PyPI, skipping if the version already exists
    - twine upload --skip-existing dist/* --verbose

  rules:
    - if: $CI_COMMIT_TAG
